### ISSUE TITLE
Error when attempting to run /spawn

### ISSUE THREAD

**Issue by baxzzi** [montlikadani/SetTheSpawn#10]
### Problem

When I run /spawn with the spawn already set through SetTheSpawn, it presents me with in chat: "An internal error occurred while attempting to perform this command"

### Details
Plugin version: 

Software version: 
* git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:6496349:370
* git-Paper-136 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT

Relevant plugins:  Vault (On Paper), Luckperms (On Waterfall). /spawn works if vault is removed for plugins folder

### Console error
```
[01:48:16] [Server thread/INFO]: baxzzi issued server command: /spawn
[01:48:16] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'spawn' in plugin SetTheSpawn v2.6.4
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.1.jar:git-Paper-136]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.1.jar:git-Paper-136]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:794) ~[patched_1.16.1.jar:git-Paper-136]
	at net.minecraft.server.v1_16_R1.PlayerConnection.handleCommand(PlayerConnection.java:1910) ~[patched_1.16.1.jar:git-Paper-136]
	at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1721) ~[patched_1.16.1.jar:git-Paper-136]
	at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.1.jar:git-Paper-136]
	at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.1.jar:git-Paper-136]
	at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.1.jar:git-Paper-136]
	at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[patched_1.16.1.jar:git-Paper-136]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.1.jar:git-Paper-136]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.1.jar:git-Paper-136]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.1.jar:git-Paper-136]
	at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1137) ~[patched_1.16.1.jar:git-Paper-136]
	at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1130) ~[patched_1.16.1.jar:git-Paper-136]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.1.jar:git-Paper-136]
	at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1091) ~[patched_1.16.1.jar:git-Paper-136]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1005) ~[patched_1.16.1.jar:git-Paper-136]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-136]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.lang.UnsupportedOperationException: SuperPerms no group permissions.
	at net.milkbowl.vault.permission.plugins.Permission_SuperPerms.getPrimaryGroup(Permission_SuperPerms.java:96) ~[?:?]
	at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:679) ~[?:?]
	at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:691) ~[?:?]
	at hu.montlikadani.setthespawn.SetTheSpawn.checkTasks(SetTheSpawn.java:659) ~[?:?]
	at hu.montlikadani.setthespawn.commands.SpawnCmd.onCommand(SpawnCmd.java:45) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.1.jar:git-Paper-136]
	... 18 more
```

### Configuration file(s)

config.yml: https://pastebin.com/yRj2yMUN

### Screenshots (optional)

![image](https://user-images.githubusercontent.com/68846447/90974817-7cc1b480-e4e3-11ea-9458-30f8fa072472.png)

**Comment by baxzzi** [comment]
That makes more sense, the only solution I can think of is to add LuckPerms in each server with the same sql database.
