### ISSUE TITLE
Multiplecommands gave this error

### ISSUE THREAD

**Issue by MrKiller01** [montlikadani/SetTheSpawn#3]
`[17:04:47 WARN]: [SetTheSpawn] There was an error. Please report it here:
https://github.com/montlikadani/SetTheSpawn/issues
[17:05:02 INFO]: Mr_Killer01 issued server command: /setthespawn importessential
sspawn
[17:05:02 WARN]: java.lang.NullPointerException
[17:05:02 WARN]:        at org.bukkit.ChatColor.translateAlternateColorCodes(Cha
tColor.java:324)
[17:05:02 WARN]:        at hu.montlikadani.SetTheSpawn.SetTheSpawn.colorMsg(SetT
heSpawn.java:872)
[17:05:02 WARN]:        at hu.montlikadani.SetTheSpawn.SetTheSpawn.getMsg(SetThe
Spawn.java:749)
[17:05:02 WARN]:        at hu.montlikadani.SetTheSpawn.Commands.onCommand(Comman
ds.java:213)
[17:05:02 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginComman
d.java:44)
[17:05:02 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCo
mmandMap.java:139)
[17:05:02 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchC
ommand(CraftServer.java:704)
[17:05:02 WARN]:        at net.minecraft.server.v1_13_R2.PlayerConnection.handle
Command(PlayerConnection.java:1636)
[17:05:02 WARN]:        at net.minecraft.server.v1_13_R2.PlayerConnection.a(Play
erConnection.java:1476)
[17:05:02 WARN]:        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(Pack
etPlayInChat.java:45)
[17:05:02 WARN]:        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(Pack
etPlayInChat.java:1)
[17:05:02 WARN]:        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.l
ambda$0(PlayerConnectionUtils.java:9)
[17:05:02 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(U
nknown Source)
[17:05:02 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[17:05:02 WARN]:        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFil
e:199)
[17:05:02 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.b(Minec
raftServer.java:896)
[17:05:02 WARN]:        at net.minecraft.server.v1_13_R2.DedicatedServer.b(Dedic
atedServer.java:417)
[17:05:02 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.a(Minec
raftServer.java:831)
[17:05:02 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.run(Min
ecraftServer.java:729)
[17:05:02 WARN]:        at java.lang.Thread.run(Unknown Source)
[17:05:02 WARN]: [SetTheSpawn] There was an error. Please report it here:
https://github.com/montlikadani/SetTheSpawn/issues`
These kinda errors show up on latest spigot 1.13.2 and (oops, 2 versions behind now) when I try to figure out when I enter the server everytime, i spawn at the point where I left off, so, not what i'd expected....

**Comment by montlikadani** [comment]
Do you modified something in the messages.yml file?

**Comment by montlikadani** [comment]
Fixed in the latest version.
