### ISSUE TITLE
why i cant see the progressbar when i spawn

### ISSUE THREAD

**Issue by wushiwuwendong** [montlikadani/SetTheSpawn#4]
Hello,i like this plugin,it looks so good.But I can see the progresssbar when i spawning.My server version 1.7.10 for bukkit .And the report is as follows：
```
[03:03:40] [Server thread/INFO]: 132123 issued server command: /spawn
[03:03:40] [Server thread/WARN]: java.lang.ClassNotFoundException: net/minecraft/server/v1_7_R4/PacketPlayOutChat
[03:03:40] [Server thread/WARN]: 	at java.lang.Class.forName0(Native Method)
[03:03:40] [Server thread/WARN]: 	at java.lang.Class.forName(Unknown Source)
[03:03:40] [Server thread/WARN]: 	at hu.montlikadani.SetTheSpawn.ActionBar.sendActionBar(ActionBar.java:23)
[03:03:40] [Server thread/WARN]: 	at hu.montlikadani.SetTheSpawn.SetTheSpawn.progressBar(SetTheSpawn.java:450)
[03:03:40] [Server thread/WARN]: 	at hu.montlikadani.SetTheSpawn.SetTheSpawn.access$1(SetTheSpawn.java:445)
[03:03:40] [Server thread/WARN]: 	at hu.montlikadani.SetTheSpawn.SetTheSpawn$1.run(SetTheSpawn.java:404)
[03:03:40] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
[03:03:40] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:346)
[03:03:40] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:870)
[03:03:40] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:458)
[03:03:40] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:806)
[03:03:40] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:665)
[03:03:40] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[03:04:43] [Server thread/INFO]: 132123 lost connection: Disconnected
[03:04:43] [Server thread/INFO]: 132123 left the game.
```

**Comment by montlikadani** [comment]
You're a nogger man, because you does not send the console error to pastebin.com site, or insert to a code block.

It seems you using the very outdated server version. I think you need to update to 1.8+
The 1.7 version soon will be removed.
